### ISSUE TITLE
Does not Build?

### ISSUE THREAD

**Issue by BenjaminSauder** [fcamarlinghi/expresso#1]
Hey there, I just tried your simple build description and it doesnt seem to work with the current version.

```
Error: Cannot find module 'cepy'
    at Function.Module._resolveFilename (module.js:325:15)
    at Function.Module._load (module.js:276:25)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (D:\code\js\expresso-master\scripts\tasks\exporter.js:9:14)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (D:\code\js\expresso-master\bin\build.js:16:18)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
```

i tried adding cepy from your repo too, as its not registered on npm (?) and not noted in you package.json.

so, that worked a bit but ends up at:

```
Error: Cannot find module './distrib/cepy.certificate.js'
    at Function.Module._resolveFilename (module.js:325:15)
    at Function.Module._load (module.js:276:25)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (D:\code\js\expresso-master\scripts\cepy.exporter.config.js:51:22)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.Promise.resolve.then.then.then.then [as run] (D:\code\js\expresso-master\scripts\tasks\exporter.js:16:24)
    at Object.<anonymous> (D:\code\js\expresso-master\bin\build.js:19:10)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Function.Module.runMain (module.js:441:10)
    at startup (node.js:139:18)
    at node.js:968:3
```

now at this point i didnt want to dig any deeper, and thought it might be best to let you know hehe..

Im sure its just some silly stuff which is not correctly submitted or whatever.

Thanks.

**Comment by fcamarlinghi** [comment]
Yeah, the whole repository is still rough, and build instructions/procedure could definitely use some work too. :) Sorry about that.

_cepy_ is not on NPM (yet!) as I wanted to make it a bit more stable before publishing it, so you're correct it currently needs to be pulled down separately.

The issue you run into is due to _cepy_ not finding the certificate config file at `<project_root>/scripts/distrib/cepy.certificate.js`. The file includes the owner and password of the certificate needed to sign the output ZXP package.

I did not include that file in the repository as it's meant to be user specific. You should be able to fix the issue by creating the file manually:

``` js
module.exports = {
    owner: 'Your name',
    file: 'scripts/distrib/cepy.certificate.p12',
    password: 'Your password',
};
```

Please let me know if this fixes your build. I would like to improve this in the future, but I'm still unsure about how.

EDIT: I forgot to mention that for the plugin to work correctly, you'll need to enable Remote Connections in Photoshop preferences (with a password set to "password") or you will see an empty panel for the moment.

**Comment by BenjaminSauder** [comment]
hey thanks for your additional informations. it works perfectly fine now!
